kind: pipeline
name: default

steps:
- name: test
  image: debian
  commands:
  - echo "deb http://deb.debian.org/debian stretch main" > /etc/apt/sources.list
  - apt update -qq
  - apt install -y -qq gcc bison flex binutils wget xz-utils make
  - ./build-kernel.sh
