kind: pipeline
name: default

steps:
- name: build
  image: debian:stretch
  commands:
  - apt update -qq
  - apt install -y -qq gcc bison flex binutils wget xz-utils make libssl1.0-dev libelf-dev bc
  - ./build-kernel.sh

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
    - kernel-build/vmlinux
    - kernel-build/arch/x86/boot/bzImage
    title: Linux Lernel
    note: ${DRONE_COMMIT}
    
trigger:
  event: tag
