kind: pipeline
name: default

steps:
- name: test
  image: debian
  commands:  
  - apt update -qq
  - apt install -y -qq gcc bison flex binutils wget xz-utils make libssl1.0-dev libelf-dev bc
  - ./build-kernel.sh
  
- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: kernel-build/vmlinux
    title: Linux Lernel
    note: ${DRONE_COMMIT}
  
